import React, { useState } from "react";

const commissionList = [
  {
    id: "KCOEPL/CN/2425/16887",
    company: "EA Consultancy",
    amount: "2,17,813",
    createdOn: "20-01-2025 05:06:51 PM",
    updatedOn: "23-01-2025 08:35:54 AM",
    receivedBy: "Pranay Chouriya",
    paidBy: "Mayank Baghrecha",
    paidOn: "04-02-2025 06:00 AM",
    isDone: true,
  },
  {
    id: "KCOEPL/CN/2425/15731",
    company: "EA Consultancy",
    amount: "2,35,483",
    createdOn: "31-12-2024 06:13:47 PM",
    updatedOn: "30-01-2025 12:25:33 PM",
    receivedBy: "Pranay Chouriya",
    paidBy: "Mayank Baghrecha",
    paidOn: "04-02-2025 06:00 AM",
    isDone: true,
  },
];

const CommissionPanel = () => {
  const [selected, setSelected] = useState(commissionList[0]);

  return (
    <div className="flex flex-col md:flex-row p-4 gap-4 max-w-full overflow-x-hidden">
      {/* Left Panel */}
      <div className="md:w-1/2 w-full">
        {commissionList.map((item, index) => (
          <div
            key={index}
            onClick={() => setSelected(item)}
            className={`border rounded-md p-4 mb-3 cursor-pointer ${
              selected.id === item.id
                ? "bg-brandRed-50 border-brandRed"
                : "bg-white"
            }`}
          >
            <div className="flex justify-between items-center flex-wrap gap-2">
              <h3 className="text-sm font-bold">{item.id}</h3>
              <span className="bg-green-600 text-white text-xs font-semibold px-2 py-1 rounded">
                Commission Payment Done
              </span>
            </div>
            <p className="text-sm mt-1 text-gray-700">{item.company}</p>
            <p className="text-sm mt-1">
              <span className="font-semibold">Commission Amount is </span>
              <span className="text-brandRed-700 font-bold">INR {item.amount}</span>
            </p>
            <p className="text-sm mt-1">
              <span className="font-semibold">Created On:</span> {item.createdOn}
            </p>
            <p className="text-sm mt-1">
              <span className="font-semibold">Last Updated On:</span> {item.updatedOn}
            </p>
          </div>
        ))}

        {/* Pagination */}
        <div className="flex justify-between items-center mt-2 flex-wrap gap-3">
          <div className="flex items-center space-x-2">
            <button className="px-2 py-1 bg-brandRed text-white text-sm rounded">
              &lt;
            </button>
            <span className="px-3 py-1 bg-brandRed text-white text-sm rounded">
              1
            </span>
            <button className="px-2 py-1 bg-brandRed text-white text-sm rounded">
              &gt;
            </button>
          </div>
          <select className="border rounded px-2 py-1 text-sm">
            <option>25/page</option>
            <option>50/page</option>
            <option>100/page</option>
          </select>
        </div>
      </div>

      {/* Right Panel */}
      <div className="md:w-1/2 w-full bg-[#f7fafd] p-4 rounded-md shadow-sm">
        <div className="flex justify-between items-start flex-wrap gap-2 mb-2">
          <h3 className="font-bold">{selected.id}</h3>
          <span className="bg-green-600 text-white text-xs font-semibold px-2 py-1 rounded">
            Commission Payment Done
          </span>
        </div>
        <p className="text-sm text-gray-700 mb-2">{selected.company}</p>
        <p className="text-sm mb-4">
          <span className="font-semibold">Commission Amount is </span>
          <span className="text-brandRed-700 font-bold">INR {selected.amount}</span>
        </p>

        <div className="flex flex-wrap gap-2 mb-4">
          <button className="border border-brandRed text-brandRed text-sm px-3 py-1 rounded">
            Download Invoice
          </button>
          <button className="border border-brandRed text-brandRed text-sm px-3 py-1 rounded">
            View Payment Remarks
          </button>
          <button className="border border-brandRed text-brandRed text-sm px-3 py-1 rounded">
            View Note
          </button>
          <button className="border border-brandRed text-brandRed text-sm px-3 py-1 rounded">
            Download Note
          </button>
        </div>

        <hr className="mb-4" />

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
          <div>
            <p className="font-semibold">Generated By:</p>
            <p className="mb-2">{selected.receivedBy}</p>

            <p className="font-semibold">Date Received On:</p>
            <p className="mb-2">{selected.createdOn}</p>

            <p className="font-semibold">Last Updated On:</p>
            <p>{selected.updatedOn}</p>
          </div>
          <div>
            <p className="font-semibold">Paid By:</p>
            <p className="mb-2">{selected.paidBy}</p>

            <p className="font-semibold">Date of Payment:</p>
            <p>{selected.paidOn}</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CommissionPanel;
